version: '3'
services:
  app:
    build: .
    ports:
      - 9050:9050
    volumes:
      - .:/usr/src/contact-app
      - /usr/src/contact-app/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh
